from __future__ import annotations

import io

from pharaoh.assetlib.api import get_asset_finder, register_asset

data = b"""<div>
<p>This HTML text was generated by an asset script!</p>
</div>"""
asset1 = register_asset(
    "raw.html",
    {"label": "MANUAL_REGISTRY", "foo": "bar"},
    template="raw_html",
    data=io.BytesIO(data),
    component="dummy",
)

data = b""".. important:: This reStructuredText text was generated by an asset script!"""
asset2 = register_asset(
    "raw.rst", {"label": "MANUAL_REGISTRY", "foo": "baz"}, template="raw_rst", data=io.BytesIO(data), component="dummy"
)

data = b'This text was generated by an asset script and will be included via "literalinclude"'
asset3 = register_asset(
    "raw.txt", {"label": "MANUAL_REGISTRY", "foo": "baz"}, template="raw_txt", data=io.BytesIO(data), component="dummy"
)


finder = get_asset_finder()
finder.discover_assets()

assert finder.get_asset_by_id(asset1.id) == asset1
assert finder.get_asset_by_id(asset2.id) == asset2
assert finder.get_asset_by_id(asset3.id) == asset3
