# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
    tests/templates/.*|
  )$
repos:
  - repo: https://gitlab.intra.infineon.com/public-mirror/github.com/astral-sh/ruff-pre-commit.git
    rev: v0.1.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --unsafe-fixes]
      - id: ruff-format
  - repo: https://gitlab.intra.infineon.com/public-mirror/github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        types: [text]
      - id: end-of-file-fixer
        types: [text]
      - id: check-added-large-files
      - id: check-yaml
