version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - python docs/cli/generate_cli_command_docs.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
