import io

import plotly.express as px

from pharaoh.assetlib.api import metadata_context, register_asset

df = px.data.iris()
fig = px.scatter(
    data_frame=df,
    x="sepal_width",
    y="sepal_length",
    color="species",
    symbol="species",
    title="A title",
)

with metadata_context(label="plot"):
    fig.write_html(file="iris_scatter.html")

data = b'This text was generated by an asset script and will be included via "literalinclude"'
register_asset("mytxt.txt", {"label": "txt"}, template="raw_txt", data=io.BytesIO(data))
