from pharaoh.assetlib.api import register_asset

fname = "raw.html"
with open(fname, "w") as f:
    f.write(
        """<div>
<p>This HTML text was generated by an asset script!</p>
</div>"""
    )
register_asset(fname, {"label": "MANUAL_REGISTRY", "foo": "bar"}, template="raw_html")


fname = "raw.rst"
with open(fname, "w") as f:
    f.write(""".. important:: This reStructuredText text was generated by an asset script!""")
register_asset(fname, {"label": "MANUAL_REGISTRY", "foo": "baz"}, template="raw_rst")


fname = "raw.txt"
with open(fname, "w") as f:
    f.write('This text was generated by an asset script and will be included via "literalinclude"')
register_asset(fname, {"label": "MANUAL_REGISTRY", "foo": "baz"}, template="raw_txt")
