#!/bin/bash -e

#######################
###  Errorhandling  ###
#######################

# not invented here. taken from: https://www.shellscript.sh/exitcodes.html
check_errs()
{
  # Function. Parameter 1 is the return code
  # Para. 2 is text to display on failure.
  if [ "${1}" -ne "0" ]; then
    echo "[ERROR]   ${1} : ${2}"
    # as a bonus, make our script exit with the right error code.
    # shellcheck disable=SC2086 # we want to retain the return code as integer, not string
    exit ${1}
  fi
}

# not invented here. taken from: https://www.shellscript.sh/tips/bash-e/
trap die ERR

die()
{
  # shellcheck disable=SC2128 # we only need the first line anyway
  echo "[ERROR]   Failed at line $BASH_LINENO"
  exit 1
}
