#!/bin/bash

set -e

# use shared error handling boilerplate
source ci/errorhandling


###################
###  Constants  ###
###################
REPO_UPSTREAM_SOURCES='https://artifactory.intra.infineon.com/artifactory/pypi-des-pyverify-local'


if [[ $EXECUTOR_NUMBER ]]; then
    # Use shared TOX workdir on Jenkins for each executor.
    # Each Jenkins executor will have a dedicated and shared TOX workdir where the tox envs are going to be created.
    # This is pulled out from the repo on purpose, otherwise Jenkins jobs would pile up a lot of virtual envs inside
    # the workspace for each branch.
    export JENKINSTOXWORKDIR=../.tox_executor_$EXECUTOR_NUMBER
    # Move pips wheel cache into the tox workdir so it doesn't pollute the C-drive using it's standard location.
    # This also makes it easier to do clean builds if you just have to delete the tox workdir for all the involved caches
    # to be invalidated.
    export PIP_CACHE_DIR=$JENKINSTOXWORKDIR/pip/cache
    mkdir -p $PIP_CACHE_DIR
fi

INTERPRETERS=("python.3.9.7" "python.3.10.7" "python.3.11.3")

pushd ci
    if [[ ! -f 7za.exe ]]; then
        echo "Fetching 7-zip"
        curl -s "${REPO_UPSTREAM_SOURCES}/tools/7za.exe" -o "7za.exe"
    fi
    for i in "${!INTERPRETERS[@]}"; do
        # Download Python interpreter and unpack
        PYTHON_NUPKG="${INTERPRETERS[i]}.nupkg"
        PYTHON_BASENAME="${PYTHON_NUPKG%.nupkg}"
        PYTHON_ROOT="$(pwd)/${PYTHON_BASENAME}/tools"
        PYTHON_BIN="${PYTHON_ROOT}/python.exe"
        PYTHON_SCRIPTS="${PYTHON_ROOT}/Scripts"
        # Append PATH
        PATH="${PYTHON_ROOT}:${PYTHON_SCRIPTS}:${PATH}"

        if [[ ! -f "${PYTHON_NUPKG}" ]]; then
            echo "Fetching package ${PYTHON_NUPKG}"
            curl -s "${REPO_UPSTREAM_SOURCES}/portable-python/${PYTHON_NUPKG}" -o "${PYTHON_NUPKG}"
        fi
        if [[ ! -d "${PYTHON_BASENAME}" ]]; then
            ./7za.exe x -o"${PYTHON_BASENAME}" "${PYTHON_NUPKG}" -aos

            # Install dev dependencies (just tox and wheel, everything else is handled by tox)
            python -m pip install --upgrade pip wheel tox
        fi
    done
popd

export TOX_PARALLEL_NO_SPINNER="1"  # Disable rotating spinner in parallel mode
# overwrite the static username that will be returned by getpass.getuser().
# Jenkins slaves sometimes have a domain prefix inside the username like eu\... which may lead to problems
# if the username is used inside file paths
export LOGNAME=jenkins

set
