#!/bin/bash

. ./ci/set_env

echo "Running tox..."
export PYTEST_XDIST_AUTO_NUM_WORKERS="0"
tox run-parallel --result-json ./ci/$(basename $BASH_SOURCE).json --skip-missing-interpreter false --recreate
