name: check
on:
  push:
    tags-ignore: ["**"]
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.11"
          - "3.10"
          - "3.9"
        os:
#          - ubuntu-latest
          - windows-latest
    steps:
      - name: Setup python for tox
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install tox
        run: python -m pip install tox
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Setup test suite
        run: tox r -e py${{ matrix.py }} -vv --notest
      - name: Run test suite
        run: tox r -e py${{ matrix.py }} --skip-pkg-install
        env:
          CI_RUN: "yes"
          DIFF_AGAINST: HEAD
          PYTEST_XDIST_AUTO_NUM_WORKERS: 0
