name: Matrix Tests
on:
  push:
    tags-ignore: ["**"]
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python ${{ matrix.py }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Run test suite
        run: hatch run all.py${{ matrix.py }}:cov
        env:
          PYTEST_XDIST_AUTO_NUM_WORKERS: 0
      - name: On fail upload pytest results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: pytest-results-${{ matrix.os }}-${{ matrix.py }}
          path: |
            .tmp/pytest
            !/**/*.zip
            !/**/_static
