name: Release to PyPI
on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pharaoh-report
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Build package
        run: hatch build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          packages-dir: dist/
          skip-existing: true
          verbose: true
          print-hash: true
