name: Release to PyPI
on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pharaoh-report
    permissions:
      id-token: write
    steps:
      - name: Setup python to build package
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build
        run: python -m pip install build
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build package
        run: pyproject-build -s -w . -o dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          packages-dir: dist/
          skip-existing: true
          verbose: true
          print-hash: true
